export const UNIVERSE_STOCKS= [
  { ticker: "AAPL", name: "Apple Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "MSFT", name: "Microsoft Corp.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "GOOGL", name: "Alphabet Inc. Class A", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "GOOG", name: "Alphabet Inc. Class C", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary", exchange: "NASDAQ" },
  { ticker: "META", name: "Meta Platforms Inc.", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "NVDA", name: "NVIDIA Corp.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "TSLA", name: "Tesla Inc.", sector: "Consumer Discretionary", exchange: "NASDAQ" },
  { ticker: "NFLX", name: "Netflix Inc.", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "AMD", name: "Advanced Micro Devices Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "INTC", name: "Intel Corp.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "AVGO", name: "Broadcom Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "QCOM", name: "Qualcomm Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "ADBE", name: "Adobe Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "CRM", name: "Salesforce Inc.", sector: "Technology", exchange: "NYSE" },
  { ticker: "ORCL", name: "Oracle Corp.", sector: "Technology", exchange: "NYSE" },
  { ticker: "CSCO", name: "Cisco Systems Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "INTU", name: "Intuit Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "IBM", name: "International Business Machines", sector: "Technology", exchange: "NYSE" },
  { ticker: "TXN", name: "Texas Instruments Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "AMAT", name: "Applied Materials Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "LRCX", name: "Lam Research Corp.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "KLAC", name: "KLA Corp.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "MRVL", name: "Marvell Technology Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "SNPS", name: "Synopsys Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "CDNS", name: "Cadence Design Systems Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "NOW", name: "ServiceNow Inc.", sector: "Technology", exchange: "NYSE" },
  { ticker: "SHOP", name: "Shopify Inc.", sector: "Technology", exchange: "NYSE" },
  { ticker: "SNOW", name: "Snowflake Inc.", sector: "Technology", exchange: "NYSE" },
  { ticker: "MDB", name: "MongoDB Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "CRWD", name: "CrowdStrike Holdings Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "PANW", name: "Palo Alto Networks Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "FTNT", name: "Fortinet Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "NET", name: "Cloudflare Inc.", sector: "Technology", exchange: "NYSE" },
  { ticker: "ZS", name: "Zscaler Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "OKTA", name: "Okta Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "DDOG", name: "Datadog Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "PLTR", name: "Palantir Technologies Inc.", sector: "Technology", exchange: "NYSE" },
  { ticker: "UBER", name: "Uber Technologies Inc.", sector: "Technology", exchange: "NYSE" },
  { ticker: "LYFT", name: "Lyft Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "ABNB", name: "Airbnb Inc.", sector: "Consumer Discretionary", exchange: "NASDAQ" },
  { ticker: "RBLX", name: "Roblox Corp.", sector: "Communication Services", exchange: "NYSE" },
  { ticker: "ZM", name: "Zoom Video Communications Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "SQ", name: "Block Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "PYPL", name: "PayPal Holdings Inc.", sector: "Financials", exchange: "NASDAQ" },
  { ticker: "COIN", name: "Coinbase Global Inc.", sector: "Financials", exchange: "NASDAQ" },
  { ticker: "MSTR", name: "MicroStrategy Inc.", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "RIOT", name: "Riot Platforms Inc.", sector: "Financials", exchange: "NASDAQ" },
  { ticker: "MARA", name: "Marathon Digital Holdings", sector: "Financials", exchange: "NASDAQ" },
  { ticker: "BIDU", name: "Baidu Inc.", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "BABA", name: "Alibaba Group Holding Ltd.", sector: "Consumer Discretionary", exchange: "NYSE" },
  { ticker: "PDD", name: "PDD Holdings Inc.", sector: "Consumer Discretionary", exchange: "NASDAQ" },
  { ticker: "JD", name: "JD.com Inc.", sector: "Consumer Discretionary", exchange: "NASDAQ" },
  { ticker: "NTES", name: "NetEase Inc.", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "TCEHY", name: "Tencent Holdings Ltd.", sector: "Communication Services", exchange: "OTC" },
  { ticker: "NIO", name: "NIO Inc.", sector: "Automotive", exchange: "NYSE" },
  { ticker: "LI", name: "Li Auto Inc.", sector: "Automotive", exchange: "NASDAQ" },
  { ticker: "XPEV", name: "XPeng Inc.", sector: "Automotive", exchange: "NYSE" },
  { ticker: "TSM", name: "Taiwan Semiconductor Mfg.", sector: "Technology", exchange: "NYSE" },
  { ticker: "ASML", name: "ASML Holding NV", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "ARM", name: "Arm Holdings plc", sector: "Technology", exchange: "NASDAQ" },
  { ticker: "SAP", name: "SAP SE", sector: "Technology", exchange: "NYSE" },
  { ticker: "ADYEN", name: "Adyen NV", sector: "Financials", exchange: "EURONEXT" },
  { ticker: "SONY", name: "Sony Group Corp.", sector: "Communication Services", exchange: "NYSE" },
  { ticker: "NTDOY", name: "Nintendo Co. Ltd.", sector: "Communication Services", exchange: "OTC" },
  { ticker: "TOYOF", name: "Toyota Motor Corp.", sector: "Automotive", exchange: "OTC" },
  { ticker: "TM", name: "Toyota Motor Corp. ADR", sector: "Automotive", exchange: "NYSE" },
  { ticker: "HMC", name: "Honda Motor Co. Ltd.", sector: "Automotive", exchange: "NYSE" },
  { ticker: "SMFG", name: "Sumitomo Mitsui Financial Group", sector: "Financials", exchange: "NYSE" },
  { ticker: "MUFG", name: "Mitsubishi UFJ Financial Group", sector: "Financials", exchange: "NYSE" },
  { ticker: "V", name: "Visa Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "MA", name: "Mastercard Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "AXP", name: "American Express Co.", sector: "Financials", exchange: "NYSE" },
  { ticker: "JPM", name: "JPMorgan Chase & Co.", sector: "Financials", exchange: "NYSE" },
  { ticker: "BAC", name: "Bank of America Corp.", sector: "Financials", exchange: "NYSE" },
  { ticker: "WFC", name: "Wells Fargo & Co.", sector: "Financials", exchange: "NYSE" },
  { ticker: "C", name: "Citigroup Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "GS", name: "Goldman Sachs Group Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "MS", name: "Morgan Stanley", sector: "Financials", exchange: "NYSE" },
  { ticker: "BLK", name: "BlackRock Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "SCHW", name: "Charles Schwab Corp.", sector: "Financials", exchange: "NYSE" },
  { ticker: "TROW", name: "T. Rowe Price Group", sector: "Financials", exchange: "NASDAQ" },
  { ticker: "BRK.B", name: "Berkshire Hathaway Inc. Class B", sector: "Financials", exchange: "NYSE" },
  { ticker: "BRK.A", name: "Berkshire Hathaway Inc. Class A", sector: "Financials", exchange: "NYSE" },
  { ticker: "SPGI", name: "S&P Global Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "ICE", name: "Intercontinental Exchange Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "MMC", name: "Marsh & McLennan Cos.", sector: "Financials", exchange: "NYSE" },
  { ticker: "AON", name: "Aon plc", sector: "Financials", exchange: "NYSE" },
  { ticker: "SOFI", name: "SoFi Technologies Inc.", sector: "Financials", exchange: "NASDAQ" },
  { ticker: "AIG", name: "American International Group", sector: "Financials", exchange: "NYSE" },
  { ticker: "MET", name: "MetLife Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "PRU", name: "Prudential Financial Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "UNH", name: "UnitedHealth Group Inc.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "HUM", name: "Humana Inc.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "CI", name: "The Cigna Group", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "ELV", name: "Elevance Health Inc.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "PFE", name: "Pfizer Inc.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "MRK", name: "Merck & Co. Inc.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "LLY", name: "Eli Lilly and Co.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "ABBV", name: "AbbVie Inc.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "BMY", name: "Bristol-Myers Squibb Co.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "GILD", name: "Gilead Sciences Inc.", sector: "Healthcare", exchange: "NASDAQ" },
  { ticker: "AMGN", name: "Amgen Inc.", sector: "Healthcare", exchange: "NASDAQ" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals", sector: "Healthcare", exchange: "NASDAQ" },
  { ticker: "ISRG", name: "Intuitive Surgical Inc.", sector: "Healthcare", exchange: "NASDAQ" },
  { ticker: "MDT", name: "Medtronic plc", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "ABT", name: "Abbott Laboratories", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "SYK", name: "Stryker Corp.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "BSX", name: "Boston Scientific Corp.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "ZBH", name: "Zimmer Biomet Holdings", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "EW", name: "Edwards Lifesciences Corp.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "DHR", name: "Danaher Corp.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "TMO", name: "Thermo Fisher Scientific Inc.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "ILMN", name: "Illumina Inc.", sector: "Healthcare", exchange: "NASDAQ" },
  { ticker: "CRSP", name: "CRISPR Therapeutics AG", sector: "Healthcare", exchange: "NASDAQ" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals Inc.", sector: "Healthcare", exchange: "NASDAQ" },
  { ticker: "CVS", name: "CVS Health Corp.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "WBA", name: "Walgreens Boots Alliance", sector: "Healthcare", exchange: "NASDAQ" },
  { ticker: "CNC", name: "Centene Corp.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "HCA", name: "HCA Healthcare Inc.", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "UHS", name: "Universal Health Services", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "WMT", name: "Walmart Inc.", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "COST", name: "Costco Wholesale Corp.", sector: "Consumer Staples", exchange: "NASDAQ" },
  { ticker: "TGT", name: "Target Corp.", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "HD", name: "The Home Depot Inc.", sector: "Consumer Discretionary", exchange: "NYSE" },
  { ticker: "LOW", name: "Lowe's Companies Inc.", sector: "Consumer Discretionary", exchange: "NYSE" },
  { ticker: "NKE", name: "Nike Inc.", sector: "Consumer Discretionary", exchange: "NYSE" },
  { ticker: "LULU", name: "Lululemon Athletica Inc.", sector: "Consumer Discretionary", exchange: "NASDAQ" },
  { ticker: "MCD", name: "McDonald's Corp.", sector: "Consumer Discretionary", exchange: "NYSE" },
  { ticker: "SBUX", name: "Starbucks Corp.", sector: "Consumer Discretionary", exchange: "NASDAQ" },
  { ticker: "YUM", name: "Yum! Brands Inc.", sector: "Consumer Discretionary", exchange: "NYSE" },
  { ticker: "CMG", name: "Chipotle Mexican Grill Inc.", sector: "Consumer Discretionary", exchange: "NYSE" },
  { ticker: "DPZ", name: "Domino's Pizza Inc.", sector: "Consumer Discretionary", exchange: "NYSE" },
  { ticker: "BKNG", name: "Booking Holdings Inc.", sector: "Consumer Discretionary", exchange: "NASDAQ" },
  { ticker: "EXPE", name: "Expedia Group Inc.", sector: "Consumer Discretionary", exchange: "NASDAQ" },
  { ticker: "MAR", name: "Marriott International Inc.", sector: "Consumer Discretionary", exchange: "NASDAQ" },
  { ticker: "HLT", name: "Hilton Worldwide Holdings", sector: "Consumer Discretionary", exchange: "NYSE" },
  { ticker: "RCL", name: "Royal Caribbean Group", sector: "Consumer Discretionary", exchange: "NYSE" },
  { ticker: "CCL", name: "Carnival Corp.", sector: "Consumer Discretionary", exchange: "NYSE" },
  { ticker: "NCLH", name: "Norwegian Cruise Line Holdings", sector: "Consumer Discretionary", exchange: "NYSE" },
  { ticker: "DIS", name: "The Walt Disney Co.", sector: "Communication Services", exchange: "NYSE" },
  { ticker: "WBD", name: "Warner Bros. Discovery Inc.", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "PARA", name: "Paramount Global", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "ROKU", name: "Roku Inc.", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "SPOT", name: "Spotify Technology SA", sector: "Communication Services", exchange: "NYSE" },
  { ticker: "EA", name: "Electronic Arts Inc.", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "TTWO", name: "Take-Two Interactive Software", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "T", name: "AT&T Inc.", sector: "Communication Services", exchange: "NYSE" },
  { ticker: "VZ", name: "Verizon Communications Inc.", sector: "Communication Services", exchange: "NYSE" },
  { ticker: "TMUS", name: "T-Mobile US Inc.", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "CHTR", name: "Charter Communications Inc.", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "CMCSA", name: "Comcast Corp.", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "XOM", name: "Exxon Mobil Corp.", sector: "Energy", exchange: "NYSE" },
  { ticker: "CVX", name: "Chevron Corp.", sector: "Energy", exchange: "NYSE" },
  { ticker: "COP", name: "ConocoPhillips", sector: "Energy", exchange: "NYSE" },
  { ticker: "OXY", name: "Occidental Petroleum Corp.", sector: "Energy", exchange: "NYSE" },
  { ticker: "SHEL", name: "Shell plc", sector: "Energy", exchange: "NYSE" },
  { ticker: "BP", name: "BP plc", sector: "Energy", exchange: "NYSE" },
  { ticker: "TTE", name: "TotalEnergies SE", sector: "Energy", exchange: "NYSE" },
  { ticker: "EQNR", name: "Equinor ASA", sector: "Energy", exchange: "NYSE" },
  { ticker: "NEE", name: "NextEra Energy Inc.", sector: "Utilities", exchange: "NYSE" },
  { ticker: "DUK", name: "Duke Energy Corp.", sector: "Utilities", exchange: "NYSE" },
  { ticker: "SO", name: "Southern Company", sector: "Utilities", exchange: "NYSE" },
  { ticker: "AEP", name: "American Electric Power", sector: "Utilities", exchange: "NASDAQ" },
  { ticker: "SRE", name: "Sempra Energy", sector: "Utilities", exchange: "NYSE" },
  { ticker: "PLD", name: "Prologis Inc.", sector: "Real Estate", exchange: "NYSE" },
  { ticker: "AMT", name: "American Tower Corp.", sector: "Real Estate", exchange: "NYSE" },
  { ticker: "EQIX", name: "Equinix Inc.", sector: "Real Estate", exchange: "NASDAQ" },
  { ticker: "SPG", name: "Simon Property Group Inc.", sector: "Real Estate", exchange: "NYSE" },
  { ticker: "O", name: "Realty Income Corp.", sector: "Real Estate", exchange: "NYSE" },
  { ticker: "PSA", name: "Public Storage", sector: "Real Estate", exchange: "NYSE" },
  { ticker: "DLR", name: "Digital Realty Trust Inc.", sector: "Real Estate", exchange: "NYSE" },
  { ticker: "WELL", name: "Welltower Inc.", sector: "Real Estate", exchange: "NYSE" },
  { ticker: "VTR", name: "Ventas Inc.", sector: "Real Estate", exchange: "NYSE" },
  { ticker: "ARE", name: "Alexandria Real Estate Equities", sector: "Real Estate", exchange: "NYSE" },
  { ticker: "LIN", name: "Linde plc", sector: "Materials", exchange: "NYSE" },
  { ticker: "APD", name: "Air Products and Chemicals Inc.", sector: "Materials", exchange: "NYSE" },
  { ticker: "SHW", name: "Sherwin-Williams Co.", sector: "Materials", exchange: "NYSE" },
  { ticker: "PPG", name: "PPG Industries Inc.", sector: "Materials", exchange: "NYSE" },
  { ticker: "ECL", name: "Ecolab Inc.", sector: "Materials", exchange: "NYSE" },
  { ticker: "NUE", name: "Nucor Corp.", sector: "Materials", exchange: "NYSE" },
  { ticker: "CLF", name: "Cleveland-Cliffs Inc.", sector: "Materials", exchange: "NYSE" },
  { ticker: "FCX", name: "Freeport-McMoRan Inc.", sector: "Materials", exchange: "NYSE" },
  { ticker: "BHP", name: "BHP Group Ltd.", sector: "Materials", exchange: "NYSE" },
  { ticker: "RIO", name: "Rio Tinto plc", sector: "Materials", exchange: "NYSE" },
  { ticker: "VALE", name: "Vale S.A.", sector: "Materials", exchange: "NYSE" },
  { ticker: "SQM", name: "Sociedad Química y Minera", sector: "Materials", exchange: "NYSE" },
  { ticker: "ALB", name: "Albemarle Corp.", sector: "Materials", exchange: "NYSE" },
  { ticker: "MOS", name: "The Mosaic Company", sector: "Materials", exchange: "NYSE" },
  { ticker: "NESN.SW", name: "Nestlé S.A.", sector: "Consumer Staples", exchange: "SIX" },
  { ticker: "RHHBY", name: "Roche Holding AG", sector: "Healthcare", exchange: "OTC" },
  { ticker: "NVO", name: "Novo Nordisk A/S", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "SIEGY", name: "Siemens AG", sector: "Industrials", exchange: "OTC" },
  { ticker: "DTEGY", name: "Deutsche Telekom AG", sector: "Communication Services", exchange: "OTC" },
  { ticker: "SAN", name: "Banco Santander S.A.", sector: "Financials", exchange: "NYSE" },
  { ticker: "CRH", name: "CRH plc", sector: "Materials", exchange: "NYSE" },
  { ticker: "PH", name: "Parker-Hannifin Corp.", sector: "Industrials", exchange: "NYSE" },
  { ticker: "AME", name: "AMETEK Inc.", sector: "Industrials", exchange: "NYSE" },
  { ticker: "ROP", name: "Roper Technologies Inc.", sector: "Industrials", exchange: "NYSE" },
  { ticker: "ITW", name: "Illinois Tool Works", sector: "Industrials", exchange: "NYSE" },
  { ticker: "ETN", name: "Eaton Corp.", sector: "Industrials", exchange: "NYSE" },
  { ticker: "EMR", name: "Emerson Electric", sector: "Industrials", exchange: "NYSE" },
  { ticker: "DOV", name: "Dover Corp.", sector: "Industrials", exchange: "NYSE" },
  { ticker: "CMI", name: "Cummins Inc.", sector: "Industrials", exchange: "NYSE" },
  { ticker: "PCAR", name: "PACCAR Inc.", sector: "Industrials", exchange: "NASDAQ" },
  { ticker: "FISV", name: "Fiserv Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "FIS", name: "Fidelity National Information Services", sector: "Financials", exchange: "NYSE" },
  { ticker: "GPN", name: "Global Payments Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "DFS", name: "Discover Financial Services", sector: "Financials", exchange: "NYSE" },
  { ticker: "ALLY", name: "Ally Financial Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "KEY", name: "KeyCorp", sector: "Financials", exchange: "NYSE" },
  { ticker: "RF", name: "Regions Financial", sector: "Financials", exchange: "NYSE" },
  { ticker: "HBAN", name: "Huntington Bancshares", sector: "Financials", exchange: "NASDAQ" },
  { ticker: "FITB", name: "Fifth Third Bancorp", sector: "Financials", exchange: "NASDAQ" },
  { ticker: "STT", name: "State Street Corp.", sector: "Financials", exchange: "NYSE" },
  { ticker: "BK", name: "Bank of New York Mellon", sector: "Financials", exchange: "NYSE" },
  { ticker: "NTRS", name: "Northern Trust Corp.", sector: "Financials", exchange: "NASDAQ" },
  { ticker: "AMP", name: "Ameriprise Financial", sector: "Financials", exchange: "NYSE" },
  { ticker: "LPLA", name: "LPL Financial Holdings", sector: "Financials", exchange: "NASDAQ" },
  { ticker: "MTB", name: "M&T Bank Corp.", sector: "Financials", exchange: "NYSE" },
  { ticker: "ZION", name: "Zions Bancorp", sector: "Financials", exchange: "NASDAQ" },
  { ticker: "PNC", name: "PNC Financial Services", sector: "Financials", exchange: "NYSE" },
  { ticker: "TFC", name: "Truist Financial", sector: "Financials", exchange: "NYSE" },
  { ticker: "USB", name: "U.S. Bancorp", sector: "Financials", exchange: "NYSE" },
  { ticker: "CMA", name: "Comerica Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "GE", name: "General Electric Co.", sector: "Industrials", exchange: "NYSE" },
  { ticker: "HON", name: "Honeywell International", sector: "Industrials", exchange: "NASDAQ" },
  { ticker: "MMM", name: "3M Company", sector: "Industrials", exchange: "NYSE" },
  { ticker: "BAESY", name: "BAE Systems plc", sector: "Industrials", exchange: "OTC" },
  { ticker: "AIR.PA", name: "Airbus SE", sector: "Industrials", exchange: "EURONEXT" },
  { ticker: "LHX", name: "L3Harris Technologies", sector: "Industrials", exchange: "NYSE" },
  { ticker: "TDG", name: "TransDigm Group", sector: "Industrials", exchange: "NYSE" },
  { ticker: "ROL", name: "Rollins Inc.", sector: "Industrials", exchange: "NYSE" },
  { ticker: "CTAS", name: "Cintas Corp.", sector: "Industrials", exchange: "NASDAQ" },
  { ticker: "EXPD", name: "Expeditors International", sector: "Industrials", exchange: "NASDAQ" },
  { ticker: "DAL", name: "Delta Air Lines Inc.", sector: "Industrials", exchange: "NYSE" },
  { ticker: "UAL", name: "United Airlines Holdings", sector: "Industrials", exchange: "NASDAQ" },
  { ticker: "AAL", name: "American Airlines Group", sector: "Industrials", exchange: "NASDAQ" },
  { ticker: "LUV", name: "Southwest Airlines", sector: "Industrials", exchange: "NYSE" },
  { ticker: "JBLU", name: "JetBlue Airways", sector: "Industrials", exchange: "NASDAQ" },
  { ticker: "RYAAY", name: "Ryanair Holdings", sector: "Industrials", exchange: "NASDAQ" },
  { ticker: "EADSY", name: "Airbus ADR", sector: "Industrials", exchange: "OTC" },
  { ticker: "KSU", name: "Kansas City Southern", sector: "Industrials", exchange: "NYSE" },
  { ticker: "CP", name: "Canadian Pacific Railway", sector: "Industrials", exchange: "NYSE" },
  { ticker: "CNI", name: "Canadian National Railway", sector: "Industrials", exchange: "NYSE" },
  { ticker: "LLYVK", name: "Lilly Ventures", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "TEVA", name: "Teva Pharmaceutical", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "BAX", name: "Baxter International", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "BDX", name: "Becton Dickinson", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "HOLX", name: "Hologic Inc.", sector: "Healthcare", exchange: "NASDAQ" },
  { ticker: "MASI", name: "Masimo Corp.", sector: "Healthcare", exchange: "NASDAQ" },
  { ticker: "GNRC", name: "Generac Holdings", sector: "Industrials", exchange: "NYSE" },
  { ticker: "EFX", name: "Equifax Inc.", sector: "Financials", exchange: "NYSE" },
  { ticker: "TRU", name: "TransUnion", sector: "Financials", exchange: "NYSE" },
  { ticker: "VRSK", name: "Verisk Analytics", sector: "Financials", exchange: "NASDAQ" },
  { ticker: "MO", name: "Altria Group Inc.", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "PM", name: "Philip Morris International", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "KO", name: "Coca-Cola Co.", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "PEP", name: "PepsiCo Inc.", sector: "Consumer Staples", exchange: "NASDAQ" },
  { ticker: "MDLZ", name: "Mondelez International", sector: "Consumer Staples", exchange: "NASDAQ" },
  { ticker: "CL", name: "Colgate-Palmolive", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "KMB", name: "Kimberly-Clark Corp.", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "GIS", name: "General Mills Inc.", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "K", name: "Kellogg Co.", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "TSN", name: "Tyson Foods Inc.", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "ADM", name: "Archer-Daniels-Midland", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "CPB", name: "Campbell Soup Co.", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "SJM", name: "J.M. Smucker Co.", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "STZ", name: "Constellation Brands", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "DEO", name: "Diageo plc", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "UL", name: "Unilever plc", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "BTI", name: "British American Tobacco", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "NESN.SW", name: "Nestlé S.A.", sector: "Consumer Staples", exchange: "SIX" },
  { ticker: "OR.PA", name: "L'Oréal S.A.", sector: "Consumer Staples", exchange: "EURONEXT" },
  { ticker: "SAP", name: "SAP SE", sector: "Technology", exchange: "NYSE" },
  { ticker: "SIE.DE", name: "Siemens AG", sector: "Industrials", exchange: "XETRA" },
  { ticker: "ADS.DE", name: "Adidas AG", sector: "Consumer Discretionary", exchange: "XETRA" },
  { ticker: "ALV.DE", name: "Allianz SE", sector: "Financials", exchange: "XETRA" },
  { ticker: "BMW.DE", name: "BMW AG", sector: "Automotive", exchange: "XETRA" },
  { ticker: "VOW3.DE", name: "Volkswagen AG", sector: "Automotive", exchange: "XETRA" },
  { ticker: "DTE.DE", name: "Deutsche Telekom AG", sector: "Communication Services", exchange: "XETRA" },
  { ticker: "BAS.DE", name: "BASF SE", sector: "Materials", exchange: "XETRA" },
  { ticker: "DPW.DE", name: "Deutsche Post DHL", sector: "Industrials", exchange: "XETRA" },
  { ticker: "AIR.PA", name: "Airbus SE", sector: "Industrials", exchange: "EURONEXT" },
  { ticker: "MC.PA", name: "LVMH Moët Hennessy Louis Vuitton", sector: "Consumer Discretionary", exchange: "EURONEXT" },
  { ticker: "KER.PA", name: "Kering SA", sector: "Consumer Discretionary", exchange: "EURONEXT" },
  { ticker: "BN.PA", name: "Danone SA", sector: "Consumer Staples", exchange: "EURONEXT" },
  { ticker: "ORA.PA", name: "Orange S.A.", sector: "Communication Services", exchange: "EURONEXT" },
  { ticker: "SAN.PA", name: "Sanofi S.A.", sector: "Healthcare", exchange: "EURONEXT" },
  { ticker: "ENEL.MI", name: "Enel SpA", sector: "Utilities", exchange: "BIT" },
  { ticker: "ENI.MI", name: "ENI SpA", sector: "Energy", exchange: "BIT" },
  { ticker: "ISP.MI", name: "Intesa Sanpaolo", sector: "Financials", exchange: "BIT" },
  { ticker: "STLA", name: "Stellantis NV", sector: "Automotive", exchange: "NYSE" },
  { ticker: "UBS", name: "UBS Group AG", sector: "Financials", exchange: "NYSE" },
  { ticker: "CS", name: "Credit Suisse Group", sector: "Financials", exchange: "NYSE" },
  { ticker: "BP", name: "BP plc", sector: "Energy", exchange: "NYSE" },
  { ticker: "SHEL", name: "Shell plc", sector: "Energy", exchange: "NYSE" },
  { ticker: "RDS.A", name: "Royal Dutch Shell A", sector: "Energy", exchange: "NYSE" },
  { ticker: "RDS.B", name: "Royal Dutch Shell B", sector: "Energy", exchange: "NYSE" },
  { ticker: "AZN", name: "AstraZeneca plc", sector: "Healthcare", exchange: "NASDAQ" },
  { ticker: "GSK", name: "GSK plc", sector: "Healthcare", exchange: "NYSE" },
  { ticker: "BTI", name: "British American Tobacco", sector: "Consumer Staples", exchange: "NYSE" },
  { ticker: "NG.L", name: "National Grid plc", sector: "Utilities", exchange: "LSE" },
  { ticker: "VOD", name: "Vodafone Group", sector: "Communication Services", exchange: "NASDAQ" },
  { ticker: "BARC.L", name: "Barclays plc", sector: "Financials", exchange: "LSE" },
  { ticker: "HSBA.L", name: "HSBC Holdings", sector: "Financials", exchange: "LSE" },
  { ticker: "BP.L", name: "BP plc (London)", sector: "Energy", exchange: "LSE" },
  { ticker: "ULVR.L", name: "Unilever plc", sector: "Consumer Staples", exchange: "LSE" },
  { ticker: "TSCO.L", name: "Tesco plc", sector: "Consumer Staples", exchange: "LSE" },
  { ticker: "RKT.L", name: "Reckitt Benckiser", sector: "Consumer Staples", exchange: "LSE" },
  { ticker: "DGE.L", name: "Diageo plc", sector: "Consumer Staples", exchange: "LSE" },
  { ticker: "BATS.L", name: "British American Tobacco", sector: "Consumer Staples", exchange: "LSE" },
  { ticker: "RIO.L", name: "Rio Tinto plc", sector: "Materials", exchange: "LSE" },
  { ticker: "GLEN.L", name: "Glencore plc", sector: "Materials", exchange: "LSE" },
  { ticker: "BP.L", name: "BP plc", sector: "Energy", exchange: "LSE" },
];
