// app/ai/page.tsx
export const revalidate = 10800; // 3 ore

import { cookies } from "next/headers";
import AuthGuard from "@/components/AuthGuard";
import {
  getAIInvestmentIdeas,
  type InvestmentIdea,
  type AIResult,
} 
from "../../lib/AiAdvisor";
import AiIdeaCard from "../../components/AiIdeaCard";
import { normalizeLang } from "../../lib/i18n";

import type { Quote } from "../../lib/marketData";
import { fetchQuotes } from "../../lib/marketData";
import { fetchLatestClose } from "../../lib/historyData";

export type InvestmentIdeaWithPrice = InvestmentIdea & {
  priceNow: number | null;
};

function normalizeTicker(t: string) {
  return t.trim().toUpperCase();
}

// testi header/disclaimer per lingua
const AI_TEXTS: Record<
  string,
  { title: string; subtitle: string; disclaimer: string }
> = {
  it: {
    title: "Quantivo AI",
    subtitle:
      "Le stime di performance (1 giorno, 1 settimana, 1 mese) sono generate da un modello AI su dati storici di indici, azioni e crypto, solo a scopo educativo.",
    disclaimer:
      "Le percentuali e i target mostrati sono stime ipotetiche generate da un modello AI allenato con oltre 500 indici storici. Non sono raccomandazioni di investimento. Dedica speciale a Gaia-Tentori.",
  },
  en: {
    title: "Quantivo AI",
    subtitle:
      "Performance estimates (1 day, 1 week, 1 month) are generated by an AI model on historical data for indices, stocks and crypto.",
    disclaimer:
      "Percentages and targets shown are hypothetical estimates generated by an AI model for educational purposes only. They are not real market forecasts nor investment recommendations. Special dedication to Gaia-Tentori.",
  },
  zh: {
    title: "Quantivo AI",
    subtitle:
      "绩效预估（1 天、1 周、1 个月）由 AI 模型基于指数、股票和加密资产的历史数据生成，仅供学习参考，不构成投资建议。",
    disclaimer:
      "页面中的百分比和目标价格只是由 AI 模型生成的假设性示例，仅用于教育目的，不构成真实市场预测或任何投资建议。特别致敬 Gaia-Tentori。",
  },
};

export default async function AiPage() {
  const cookieStore: any = await (cookies() as any);
  const cookieValue: string =
    cookieStore?.get?.("quantivo-lang")?.value ?? "en";

  const lang = normalizeLang(cookieValue);

  const data: AIResult = await getAIInvestmentIdeas(lang);
  const text = AI_TEXTS[lang] ?? AI_TEXTS["en"];

  // 1) prendo TUTTI i ticker dalle idee (stocks + ETF + crypto)
  const allTickers = Array.from(
    new Set(
      data.ideas
        .map((idea) => normalizeTicker(idea.ticker))
        .filter(Boolean)
    )
  );

  // 2) chiamo Finnhub per tutti questi ticker
  let liveQuotes: Quote[] = [];
  try {
    liveQuotes = await fetchQuotes(allTickers);
  } catch (err) {
    console.error("[AI page] Errore fetchQuotes Finnhub", err);
  }

  const quoteMap = new Map<string, number>();
  for (const q of liveQuotes) {
    const t = normalizeTicker(q.ticker);
    if (q.price && !Number.isNaN(q.price)) {
      quoteMap.set(t, q.price);
    }
  }

  // 3) arricchisco ogni idea con priceNow
  const ideasWithPrice: InvestmentIdeaWithPrice[] = await Promise.all(
    data.ideas.map(async (idea) => {
      const tickerNorm = normalizeTicker(idea.ticker);
      const kind = (idea as any).kind as string | undefined;
      const kindLower = (kind ?? "").toLowerCase();

      let priceNow: number | null = quoteMap.get(tickerNorm) ?? null;

      const isEtf = kindLower.includes("etf");

      // fallback ETF: se Finnhub non ha dato nulla, uso AlphaVantage (ultimo close)
      if ((priceNow === null || priceNow === 0) && isEtf) {
        try {
          const latest = await fetchLatestClose(idea.ticker);
          if (latest && !Number.isNaN(latest)) {
            priceNow = latest;
          }
        } catch (err) {
          console.error(
            "[AI page] Errore fetchLatestClose AlphaVantage per",
            idea.ticker,
            err
          );
        }
      }

      // DEBUG (puoi toglierlo dopo): logga se non siamo riusciti a trovare il prezzo
      if (priceNow === null) {
        console.warn(
          "[AI page] Nessun prezzo trovato per",
          idea.ticker,
          "kind:",
          kind
        );
      }

      return { ...idea, priceNow };
    })
  );

  return (
    <AuthGuard>
      <div className="space-y-4 p-5">
        <header className="space-y-1">
          <h1 className="text-2xl font-semibold">{text.title}</h1>
          <p className="text-xs text-slate-400">{text.subtitle}</p>
        </header>

        <section className="space-y-3">
          {ideasWithPrice.map((idea, i) => (
            <AiIdeaCard key={idea.ticker + i} idea={idea} />
          ))}
        </section>

        <p className="pt-4 text-[10px] text-slate-500">{text.disclaimer}</p>
      </div>
    </AuthGuard>
  );
}
