// app/ai/page.tsx
export const revalidate = 10800; // 3 ore

import { cookies } from "next/headers";
import AuthGuard from "@/components/AuthGuard";
import {
  getAIInvestmentIdeas,
  type InvestmentIdea,
  type AIResult,
} from "../../lib/AiAdvisor";
import type { Quote } from "../../lib/marketData";
import AiIdeaCard from "../../components/AiIdeaCard";
import { normalizeLang } from "../../lib/i18n";

// trova il prezzo per un dato ticker (se Finnhub lo ha dato)
function findQuote(ticker: string, prices: Quote[]): Quote | undefined {
  return prices.find((q) => q.ticker === ticker);
}

export type InvestmentIdeaWithPrice = InvestmentIdea & {
  priceNow: number | null;
};

// testi header/disclaimer per lingua
const AI_TEXTS: Record<
  string,
  { title: string; subtitle: string; disclaimer: string }
> = {
  it: {
    title: "Quantivo AI",
    subtitle:
      "Le stime di performance (1 giorno, 1 settimana, 1 mese) sono generate da un modello AI su dati storici di indici, azioni e crypto, solo a scopo educativo.",
    disclaimer:
      "Le percentuali e i target mostrati sono stime ipotetiche generate da un modello AI allenato con oltre 500 indici storici. Non sono raccomandazioni di investimento.",
  },
  en: {
    title: "Quantivo AI",
    subtitle:
      "Performance estimates (1 day, 1 week, 1 month) are generated by an AI model on historical data for indices, stocks and crypto.",
    disclaimer:
      "Percentages and targets shown are hypothetical estimates generated by an AI model for educational purposes only. They are not real market forecasts nor investment recommendations.",
  },
  zh: {
    title: "Quantivo AI",
    subtitle:
      "绩效预估（1 天、1 周、1 个月）由 AI 模型基于指数、股票和加密资产的历史数据生成，仅供学习参考，不构成投资建议。",
    disclaimer:
      "页面中的百分比和目标价格只是由 AI 模型生成的假设性示例，仅用于教育目的，不构成真实市场预测或任何投资建议。",
  },
};

export default async function AiPage() {
  // ✅ cookies() può essere sync o async a seconda della versione:
  // uso await + cast any così non mi interessa la firma esatta
  const cookieStore: any = await (cookies() as any);
  const cookieValue: string =
    cookieStore?.get?.("quantivo-lang")?.value ?? "en";

  const lang = normalizeLang(cookieValue); // es. "it", "en", "zh", ...

  // 📊 chiamo l'AI passando la lingua → le "reason" arrivano già tradotte
  const data: AIResult = await getAIInvestmentIdeas(lang);
  const text = AI_TEXTS[lang] ?? AI_TEXTS["en"];

  const ideasWithPrice: InvestmentIdeaWithPrice[] = data.ideas.map(
    (idea: InvestmentIdea) => {
      const quote = findQuote(idea.ticker, data.prices);
      const priceNow = quote?.price ?? null;

      return {
        ...idea,
        priceNow,
      };
    }
  );

  return (
    <AuthGuard>
      <div className="space-y-4 p-5">
        <header className="space-y-1">
          <h1 className="text-2xl font-semibold">{text.title}</h1>
          <p className="text-xs text-slate-400">{text.subtitle}</p>
        </header>

        <section className="space-y-3">
          {ideasWithPrice.map((idea, i) => (
            <AiIdeaCard key={idea.ticker + i} idea={idea} />
          ))}
        </section>

        <p className="pt-4 text-[10px] text-slate-500">{text.disclaimer}</p>
      </div>
    </AuthGuard>
  );
}
